In [32]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

# Load the data
df = pd.read_parquet("yellow_tripdata_2024-01.parquet")
print(type(df))
print(f"Rows: {df.shape[0]:,}")
print(f"Columns: {df.shape[1]}")
df.head()

<class 'pandas.DataFrame'>
Rows: 2,964,624
Columns: 19

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee
0,2,2024-01-01 00:57:55,2024-01-01 01:17:43,1.0,1.72,1.0,N,186,79,2,17.7,1.0,0.5,0.00,0.0,1.0,22.70,2.5,0.0
1,1,2024-01-01 00:03:00,2024-01-01 00:09:36,1.0,1.80,1.0,N,140,236,1,10.0,3.5,0.5,3.75,0.0,1.0,18.75,2.5,0.0
2,1,2024-01-01 00:17:06,2024-01-01 00:35:01,1.0,4.70,1.0,N,236,79,1,23.3,3.5,0.5,3.00,0.0,1.0,31.30,2.5,0.0
3,1,2024-01-01 00:36:38,2024-01-01 00:44:56,1.0,1.40,1.0,N,79,211,1,10.0,3.5,0.5,2.00,0.0,1.0,17.00,2.5,0.0
4,1,2024-01-01 00:46:51,2024-01-01 00:52:57,1.0,0.80,1.0,N,211,148,1,7.9,3.5,0.5,3.20,0.0,1.0,16.10,2.5,0.0

In [3]:
df.describe()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee
count,2.964624e+06,2964624,2964624,2.824462e+06,2.964624e+06,2.824462e+06,2.964624e+06,2.964624e+06,2.964624e+06,2.964624e+06,2.964624e+06,2.964624e+06,2.964624e+06,2.964624e+06,2.964624e+06,2.964624e+06,2.824462e+06,2.824462e+06
mean,1.754204e+00,2024-01-17 00:46:36.431092,2024-01-17 01:02:13.208130,1.339281e+00,3.652169e+00,2.069359e+00,1.660179e+02,1.651167e+02,1.161271e+00,1.817506e+01,1.451598e+00,4.833823e-01,3.335870e+00,5.270212e-01,9.756319e-01,2.680150e+01,2.256122e+00,1.411611e-01
min,1.000000e+00,2002-12-31 22:59:39,2002-12-31 23:05:41,0.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,-8.990000e+02,-7.500000e+00,-5.000000e-01,-8.000000e+01,-8.000000e+01,-1.000000e+00,-9.000000e+02,-2.500000e+00,-1.750000e+00
25%,2.000000e+00,2024-01-09 15:59:19.750000,2024-01-09 16:16:23,1.000000e+00,1.000000e+00,1.000000e+00,1.320000e+02,1.140000e+02,1.000000e+00,8.600000e+00,0.000000e+00,5.000000e-01,1.000000e+00,0.000000e+00,1.000000e+00,1.538000e+01,2.500000e+00,0.000000e+00
50%,2.000000e+00,2024-01-17 10:45:37.500000,2024-01-17 11:03:51.500000,1.000000e+00,1.680000e+00,1.000000e+00,1.620000e+02,1.620000e+02,1.000000e+00,1.280000e+01,1.000000e+00,5.000000e-01,2.700000e+00,0.000000e+00,1.000000e+00,2.010000e+01,2.500000e+00,0.000000e+00
75%,2.000000e+00,2024-01-24 18:23:52.250000,2024-01-24 18:40:29,1.000000e+00,3.110000e+00,1.000000e+00,2.340000e+02,2.340000e+02,1.000000e+00,2.050000e+01,2.500000e+00,5.000000e-01,4.120000e+00,0.000000e+00,1.000000e+00,2.856000e+01,2.500000e+00,0.000000e+00
max,6.000000e+00,2024-02-01 00:01:15,2024-02-02 13:56:52,9.000000e+00,3.127223e+05,9.900000e+01,2.650000e+02,2.650000e+02,4.000000e+00,5.000000e+03,1.425000e+01,4.000000e+00,4.280000e+02,1.159200e+02,1.000000e+00,5.000000e+03,2.500000e+00,1.750000e+00
std,4.325902e-01,NaN,NaN,8.502817e-01,2.254626e+02,9.823219e+00,6.362391e+01,6.931535e+01,5.808686e-01,1.894955e+01,1.804102e+00,1.177600e-01,3.896551e+00,2.128310e+00,2.183645e-01,2.338558e+01,8.232747e-01,4.876239e-01

In [5]:
df.dtypes

VendorID                          int32
tpep_pickup_datetime     datetime64[us]
tpep_dropoff_datetime    datetime64[us]
passenger_count                 float64
trip_distance                   float64
RatecodeID                      float64
store_and_fwd_flag                  str
PULocationID                      int32
DOLocationID                      int32
payment_type                      int64
fare_amount                     float64
extra                           float64
mta_tax                         float64
tip_amount                      float64
tolls_amount                    float64
improvement_surcharge           float64
total_amount                    float64
congestion_surcharge            float64
Airport_fee                     float64
dtype: object

In [7]:
df.isnull().sum().sort_values(ascending=False)

store_and_fwd_flag       140162
RatecodeID               140162
passenger_count          140162
Airport_fee              140162
congestion_surcharge     140162
VendorID                      0
tpep_pickup_datetime          0
tpep_dropoff_datetime         0
DOLocationID                  0
PULocationID                  0
trip_distance                 0
fare_amount                   0
payment_type                  0
extra                         0
mta_tax                       0
tolls_amount                  0
tip_amount                    0
total_amount                  0
improvement_surcharge         0
dtype: int64

In [8]:
df['fare_amount'].describe()

count    2.964624e+06
mean     1.817506e+01
std      1.894955e+01
min     -8.990000e+02
25%      8.600000e+00
50%      1.280000e+01
75%      2.050000e+01
max      5.000000e+03
Name: fare_amount, dtype: float64

In [15]:
df['pickup_hour'] = pd.to_datetime(df['tpep_pickup_datetime']).dt.hour
df.groupby('pickup_hour').count()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee
pickup_hour,,,,,,,,,,,,,,,,,,,
0,79094,79094,79094,72323,79094,72323,72323,79094,79094,79094,79094,79094,79094,79094,79094,79094,79094,72323,72323
1,53627,53627,53627,47500,53627,47500,47500,53627,53627,53627,53627,53627,53627,53627,53627,53627,53627,47500,47500
2,37517,37517,37517,33673,37517,33673,33673,37517,37517,37517,37517,37517,37517,37517,37517,37517,37517,33673,33673
3,24811,24811,24811,21902,24811,21902,21902,24811,24811,24811,24811,24811,24811,24811,24811,24811,24811,21902,21902
4,16742,16742,16742,13882,16742,13882,13882,16742,16742,16742,16742,16742,16742,16742,16742,16742,16742,13882,13882
5,18764,18764,18764,16746,18764,16746,16746,18764,18764,18764,18764,18764,18764,18764,18764,18764,18764,16746,16746
6,41429,41429,41429,37162,41429,37162,37162,41429,41429,41429,41429,41429,41429,41429,41429,41429,41429,37162,37162
7,83719,83719,83719,76926,83719,76926,76926,83719,83719,83719,83719,83719,83719,83719,83719,83719,83719,76926,76926
8,117209,117209,117209,108762,117209,108762,108762,117209,117209,117209,117209,117209,117209,117209,117209,117209,117209,108762,108762
9,128970,128970,128970,123552,128970,123552,123552,128970,128970,128970,128970,128970,128970,128970,128970,128970,128970,123552,123552
10,138778,138778,138778,134595,138778,134595,134595,138778,138778,138778,138778,138778,138778,138778,138778,138778,138778,134595,134595
11,150542,150542,150542,146221,150542,146221,146221,150542,150542,150542,150542,150542,150542,150542,150542,150542,150542,146221,146221
12,164559,164559,164559,159279,164559,159279,159279,164559,164559,164559,164559,164559,164559,164559,164559,164559,164559,159279,159279
13,169903,169903,169903,165074,169903,165074,165074,169903,169903,169903,169903,169903,169903,169903,169903,169903,169903,165074,165074
14,182898,182898,182898,177601,182898,177601,177601,182898,182898,182898,182898,182898,182898,182898,182898,182898,182898,177601,177601
15,189359,189359,189359,183606,189359,183606,183606,189359,189359,189359,189359,189359,189359,189359,189359,189359,189359,183606,183606
16,190201,190201,190201,184934,190201,184934,184934,190201,190201,190201,190201,190201,190201,190201,190201,190201,190201,184934,184934
17,206257,206257,206257,197893,206257,197893,197893,206257,206257,206257,206257,206257,206257,206257,206257,206257,206257,197893,197893
18,212788,212788,212788,202592,212788,202592,202592,212788,212788,212788,212788,212788,212788,212788,212788,212788,212788,202592,202592
19,184032,184032,184032,176369,184032,176369,176369,184032,184032,184032,184032,184032,184032,184032,184032,184032,184032,176369,176369
20,159989,159989,159989,154258,159989,154258,154258,159989,159989,159989,159989,159989,159989,159989,159989,159989,159989,154258,154258
21,160888,160888,160888,153361,160888,153361,153361,160888,160888,160888,160888,160888,160888,160888,160888,160888,160888,153361,153361
22,143261,143261,143261,135047,143261,135047,135047,143261,143261,143261,143261,143261,143261,143261,143261,143261,143261,135047,135047
23,109287,109287,109287,101204,109287,101204,101204,109287,109287,109287,109287,109287,109287,109287,109287,109287,109287,101204,101204

In [16]:
df.groupby('pickup_hour').size()

pickup_hour
0      79094
1      53627
2      37517
3      24811
4      16742
5      18764
6      41429
7      83719
8     117209
9     128970
10    138778
11    150542
12    164559
13    169903
14    182898
15    189359
16    190201
17    206257
18    212788
19    184032
20    159989
21    160888
22    143261
23    109287
dtype: int64

In [19]:
df['pickup_hour'].value_counts().sort_values(ascending=False)

pickup_hour
18    212788
17    206257
16    190201
15    189359
19    184032
14    182898
13    169903
12    164559
21    160888
20    159989
11    150542
22    143261
10    138778
9     128970
8     117209
23    109287
7      83719
0      79094
1      53627
6      41429
2      37517
3      24811
5      18764
4      16742
Name: count, dtype: int64

In [21]:
schema = {
    "vendor_id": "integer",
    "pickup_datetime": "timestamp",
    "fare_amount": "float",
    "passenger_count": "integer"
}

print(schema["fare_amount"])

float

In [22]:
schema.get("missing_col", "unknown")

'unknown'

In [39]:
for a in list(schema.keys()) :
    print(f"value - {a} and dtype - {type(a)}")

value - vendor_id and dtype - <class 'str'>
value - pickup_datetime and dtype - <class 'str'>
value - fare_amount and dtype - <class 'str'>
value - passenger_count and dtype - <class 'str'>

In [40]:
for a in list(schema.values() ):
    print(f"value - {a} and dtype - {type(a)}")

value - integer and dtype - <class 'str'>
value - timestamp and dtype - <class 'str'>
value - float and dtype - <class 'str'>
value - integer and dtype - <class 'str'>

In [43]:
for a,v in schema.items():
    print(f"key- {a} value - {v} and dtype - {type(a)}")

key- vendor_id value - integer and dtype - <class 'str'>
key- pickup_datetime value - timestamp and dtype - <class 'str'>
key- fare_amount value - float and dtype - <class 'str'>
key- passenger_count value - integer and dtype - <class 'str'>

In [44]:
float_cols = {k: v for k, v in schema.items() if v == "float"}

In [45]:
float_cols

{'fare_amount': 'float'}

In [46]:
# Merge two dicts (Python 3.9+)
extra_schema = {"tip_amount": "float"}
full_schema = schema | extra_schema

In [47]:
full_schema

{'vendor_id': 'integer',
 'pickup_datetime': 'timestamp',
 'fare_amount': 'float',
 'passenger_count': 'integer',
 'tip_amount': 'float'}

In [48]:
print(full_schema)

{'vendor_id': 'integer', 'pickup_datetime': 'timestamp', 'fare_amount': 'float', 'passenger_count': 'integer', 'tip_amount': 'float'}

In [50]:
# ── Lists — ordered, mutable ─────────────────────────────────────
columns = ["vendor_id", "pickup_datetime", "fare_amount", "tip_amount"]

# DE operations on lists
print(columns.append("total_amount") ,           # add column
columns.remove("vendor_id")    ,          # remove column
"fare_amount" in columns   ,              # True — membership check
columns[0]             ,                  # "vendor_id" — first element
columns[-1]          ,                    # last element
columns[1:3]         ,                    # slice — elements 1 and 2
len(columns)      )

None None True pickup_datetime total_amount ['fare_amount', 'tip_amount'] 4

In [54]:
print('harsh'+ ' gupta')

harsh gupta

In [57]:
actual_cols = {"vendor_id", "fare_amount", "pickup_datetime"}
actual_cols = ["vendor_id", "fare_amount", "pickup_datetime"]
type(actual_cols)

list

In [89]:
df = {
    'employee': ['harsh','tushar','vaibhavi','jack'],
    'department':['12','10','20','45']
}
df = pd.DataFrame(df)
df

# Loop with early exit — useful in validation
def find_null_column(df: pd.DataFrame) -> str | None:
    for col in df.columns:
        if df[col].isnull().any():
            return col     # return immediately when found
    return None            # no nulls found
print(find_null_column(df))

None

In [71]:
def classify_trip(distance: float) -> str:
    if distance <1:
        return "very short"
    elif distance < 5:
        return "medium"
    elif distance < 20:
        return "long"
    else:
        return "very_long"

classify_trip(7.5)

'long'

In [79]:
# Assign and check in one line — useful in DE validations
import pandas as pd

df = pd.read_parquet("yellow_tripdata_2024-01.parquet")

row_count = len(df)
print(row_count)

if (row_count := len(df)) < 1000:
    raise ValueError(f"Too few rows: {row_count}, expected at least 1000")
else:
    print('all good')

2964624
all good

In [80]:
# ── for loops ─────────────────────────────────────────────────────
months = ["2024-01", "2024-02", "2024-03"]

# Basic loop
for month in months:
    print(f"Processing month: {month}")

# enumerate — when you need index too
for i, month in enumerate(months, start=1):
    print(f"Step {i}/12: Processing {month}")

Processing month: 2024-01
Processing month: 2024-02
Processing month: 2024-03
Step 1/12: Processing 2024-01
Step 2/12: Processing 2024-02
Step 3/12: Processing 2024-03

In [81]:
# zip — loop over two lists together
sources = ["postgres", "api", "s3"]
targets = ["raw_postgres", "raw_api", "raw_s3"]

for source, target in zip(sources, targets):
    print(f"Copying {source} → {target}")

Copying postgres → raw_postgres
Copying api → raw_api
Copying s3 → raw_s3

In [9]:
a = ["John", "Charles", "Mike"]
b = ["Jenny", "Christy", "Monica", "Vicky"]
c = [10,20,40,50]
x = zip(a, b,c)
print(list(x))
for a,b in zip(a,b):
    print(a,b)

[('John', 'Jenny', 10), ('Charles', 'Christy', 20), ('Mike', 'Monica', 40)]
John Jenny
Charles Christy
Mike Monica

In [10]:
names = ["Alice", "Bob"]
scores = [85, 90]

# Note the double unpacking: (name, score)
for i, (name, score) in enumerate(zip(names, scores), start=1):
    print(f"{i}. {name} scored {score}")

1. Alice scored 85
2. Bob scored 90

In [13]:
names = ["Alice", "Bob"]
scores = [85, 90]

# Note the double unpacking: (name, score)
#for i, (name, score) in zip(names, scores),range(len(scores)):
#    print(f"{i}. {name} scored {score}")
print( range(len(scores)))
for i in range(len(scores)):
    print(i)

range(0, 2)
0
1

In [18]:
prices = [10.5, 20.0, 35.75]

for i, price in enumerate(prices):
    prices[i] = price * 0.9  # Apply 10% discount to original list
prices
prices.append(40)
prices

[9.450000000000001, 18.0, 32.175000000000004, 40]

In [20]:
matrix = [[1, 2], [3, 4], [5, 6]]

for r, row in enumerate(matrix):
    print(f"r--> {r} and row -> {row}")
    for c, val in enumerate(row):
        print(f"Value at row {r}, col {c} is {val}")

r--> 0 and row -> [1, 2]
Value at row 0, col 0 is 1
Value at row 0, col 1 is 2
r--> 1 and row -> [3, 4]
Value at row 1, col 0 is 3
Value at row 1, col 1 is 4
r--> 2 and row -> [5, 6]
Value at row 2, col 0 is 5
Value at row 2, col 1 is 6

In [21]:
# ── Basic function ────────────────────────────────────────────────
def calculate_tip_percentage(fare: float, tip: float) -> float:
    '''
    Calculate tip as percentage of fare.

    Args:
        fare: Base fare amount in dollars
        tip: Tip amount in dollars

    Returns:
        Tip percentage (0-100)
    '''
    if fare <= 0:
        return 0.0
    return round((tip / fare) * 100, 2)

In [23]:
calculate_tip_percentage(20.5,10)

48.78

In [30]:
# ── Default arguments ─────────────────────────────────────────────
def read_taxi_data(
    file_path: str,
    columns: list[str] | None = None,    # None = all columns
    max_rows: int | None = None          # None = all rows
) -> pd.DataFrame:
    df = pd.read_parquet(file_path, columns=columns)
    if max_rows:
        df = df.head(max_rows)
    return df

# Flexible calling
df_full = read_taxi_data("yellow_tripdata_2024-01.parquet")
df_small = read_taxi_data("yellow_tripdata_2024-01.parquet", max_rows=1000)
df_cols = read_taxi_data(
    "yellow_tripdata_2024-01.parquet",
    columns=["fare_amount", "tip_amount", "trip_distance"]
)

print(df_cols)

         fare_amount  tip_amount  trip_distance
0              17.70        0.00           1.72
1              10.00        3.75           1.80
2              23.30        3.00           4.70
3              10.00        2.00           1.40
4               7.90        3.20           0.80
...              ...         ...            ...
2964619        15.77        2.00           3.18
2964620        18.40        2.34           4.00
2964621        19.97        0.00           3.33
2964622        23.88        5.58           3.06
2964623        32.40        7.29           8.10

[2964624 rows x 3 columns]

In [33]:
def user_profile(**kwargs):
    for key, value in kwargs.items():
        print(f"{key}: {value}")

user_profile(name="Alice", age=25, city="NY")

name: Alice
age: 25
city: NY

In [34]:
def sum_numbers(*args):
    return sum(args)

print(sum_numbers(10, 20, 30)) # Returns 60

60

In [37]:
car = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}

x = car.get("model", 15000)

print(x)

Mustang

In [1]:
class trip:
    pass

trip1 = trip()
trip2 = trip()

print(type(trip1))

<class '__main__.trip'>

In [3]:
class trip:

    def __init__(self, fare:float, distance: float):
        self.fare = fare
        self.distance = distance

trip1 = trip(12.5,2.3)
trip2 = trip(fare=45,distance=8.7)


# Access attributes
print(trip1.fare)        # 12.5
print(trip2.distance)    # 8.7
print(trip1.fare)        # 12.5 — trip1 not affected by trip2

12.5
8.7
12.5

In [6]:
class RideShareCompany:
    # CLASS ATTRIBUTE - shared by ALL instances
    commission_rate = 0.25  # 25% commission
    total_rides = 0
    
    def __init__(self, driver_name: str):
        # INSTANCE ATTRIBUTE - unique to each instance
        self.driver_name = driver_name
        self.earnings = 0
    
    def complete_ride(self, fare: float):
        company_cut = fare * RideShareCompany.commission_rate
        driver_cut = fare - company_cut
        
        self.earnings += driver_cut  # instance attribute
        RideShareCompany.total_rides += 1  # class attribute

# Create drivers
driver_a = RideShareCompany("Alice")
driver_b = RideShareCompany("Bob")

driver_a.complete_ride(100)
driver_b.complete_ride(200)

# Instance attributes differ
print(driver_a.earnings)  # 75.0 (Alice's earnings)
print(driver_b.earnings)  # 150.0 (Bob's earnings)

# Class attribute is shared
print(RideShareCompany.total_rides)  # 2 (total across all drivers)
print(driver_a.total_rides)
print(driver_b.total_rides)

75.0
150.0
2
2
2

In [13]:
class Temperature:
    def __init__(self, celsius: float):
        self._celsius = celsius
    
    # ═══════════════════════════════════════
    # OPTION 1: Using @property (RECOMMENDED)
    # ═══════════════════════════════════════
    
    @property
    def celsius(self) -> float:
        return self._celsius
    
    @celsius.setter
    def celsius(self, value: float):
        if value > -273.15:  # Absolute zero
            raise ValueError("Temperature below absolute zero")
        self._celsius = value
    
    @property
    def fahrenheit(self) -> float:
        """Computed on-the-fly"""
        return (self._celsius * 9/5) + 32
    
    @fahrenheit.setter
    def fahrenheit(self, value: float):
        """Convert and store as Celsius"""
        self.celsius = (value - 32) * 5/9
    
    @property
    def kelvin(self) -> float:
        """Read-only computed property"""
        return self._celsius + 273.15


# Clean, intuitive usage
temp = Temperature(30)
print(temp.celsius)      # 25 — clean access
print(temp.fahrenheit)   # 77.0 — computed automatically
print(temp.kelvin)       # 298.15 — read-only

temp.fahrenheit = 100    # Set using Fahrenheit
print(temp.celsius)      # 37.78 — automatically converted

30
86.0
303.15

ValueError: Temperature below absolute zero

In [14]:
# ═══════════════════════════════════════
# OPTION 2: Using methods (OLD STYLE)
# ═══════════════════════════════════════

class TemperatureOldStyle:
    def __init__(self, celsius: float):
        self._celsius = celsius
    
    def get_celsius(self) -> float:
        return self._celsius
    
    def set_celsius(self, value: float):
        if value < -273.15:
            raise ValueError("Temperature below absolute zero")
        self._celsius = value
    
    def get_fahrenheit(self) -> float:
        return (self._celsius * 9/5) + 32
    
    def set_fahrenheit(self, value: float):
        self.set_celsius((value - 32) * 5/9)
    
    def get_kelvin(self) -> float:
        return self._celsius + 273.15


# Ugly, verbose usage
temp_old = TemperatureOldStyle(25)
print(temp_old.get_celsius())        # ❌ Verbose
print(temp_old.get_fahrenheit())     # ❌ Inconsistent with attributes
print(temp_old.get_kelvin())         # ❌ More typing

temp_old.set_fahrenheit(100)         # ❌ Ugly setter
print(temp_old.get_celsius())        # ❌ Can't just do temp_old.celsius

25
77.0
298.15
37.77777777777778

In [23]:
import pandas as pd

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Score': [85, 92, 78, 90],
    'City': ['New York', 'London', 'Paris', 'Tokyo']
}

# We set 'Name' as the index to have string labels
df = pd.DataFrame(data).set_index('Name')

# Get Bob's data
print(df.loc['Bob'])       # Label-based

# Get the second row (which is Bob)
print(df.iloc[1])          # Position-based

high_scores = df[df['Score'] > 90]
high_scores

Score        92
City     London
Name: Bob, dtype: object
Score        92
City     London
Name: Bob, dtype: object

      Score    City
Name
Bob      92  London

In [39]:
with open('../../requirements.txt', 'r') as file:
    line = file.readline()
    while line:
        # Process the line here
        print(line)
        line = file.readline()

pandas>=2.0.0

polars>=0.19.0

pyarrow>=14.0.0

pyspark==3.5.4

confluent-kafka>=2.3.0

boto3>=1.34.0

snowflake-connector-python>=3.6.0

sqlalchemy>=2.0.0

psycopg2-binary>=2.9.0

python-dotenv>=1.0.0

loguru>=0.7.0

typer>=0.9.0

rich>=13.0.0

In [42]:
with open('../../requirements.txt', 'r') as file:
    all_lines = file.readlines()

# Now you have a standard Python list
    print(all_lines)

['pandas>=2.0.0\n', 'polars>=0.19.0\n', 'pyarrow>=14.0.0\n', 'pyspark==3.5.4\n', 'confluent-kafka>=2.3.0\n', 'boto3>=1.34.0\n', 'snowflake-connector-python>=3.6.0\n', 'sqlalchemy>=2.0.0\n', 'psycopg2-binary>=2.9.0\n', 'python-dotenv>=1.0.0\n', 'loguru>=0.7.0\n', 'typer>=0.9.0\n', 'rich>=13.0.0\n']

In [5]:
import pandas as pd
import numpy as np

# load nyc data
df = pd.read_parquet("yellow_tripdata_2024-01.parquet")

#essential operation

print(df.head())
fares = df["fare_amount"].head(10)
fares

money_cols = df [['fare_amount', 'tip_amount']]
money_cols

#filtering data

valid = df[df['fare_amount']>0]
quality = df[
    (df['fare_amount']>0)&
   ( df['trip_distance']>0) &
    (df['passenger_count']>0)
]

quality.head(10)
    

#creating new column
#df[trip_]

   VendorID tpep_pickup_datetime tpep_dropoff_datetime  passenger_count  \
0         2  2024-01-01 00:57:55   2024-01-01 01:17:43              1.0
1         1  2024-01-01 00:03:00   2024-01-01 00:09:36              1.0
2         1  2024-01-01 00:17:06   2024-01-01 00:35:01              1.0
3         1  2024-01-01 00:36:38   2024-01-01 00:44:56              1.0
4         1  2024-01-01 00:46:51   2024-01-01 00:52:57              1.0

   trip_distance  RatecodeID store_and_fwd_flag  PULocationID  DOLocationID  \
0           1.72         1.0                  N           186            79
1           1.80         1.0                  N           140           236
2           4.70         1.0                  N           236            79
3           1.40         1.0                  N            79           211
4           0.80         1.0                  N           211           148

   payment_type  fare_amount  extra  mta_tax  tip_amount  tolls_amount  \
0             2         17.7    1.0      0.5        0.00           0.0
1             1         10.0    3.5      0.5        3.75           0.0
2             1         23.3    3.5      0.5        3.00           0.0
3             1         10.0    3.5      0.5        2.00           0.0
4             1          7.9    3.5      0.5        3.20           0.0

   improvement_surcharge  total_amount  congestion_surcharge  Airport_fee
0                    1.0         22.70                   2.5          0.0
1                    1.0         18.75                   2.5          0.0
2                    1.0         31.30                   2.5          0.0
3                    1.0         17.00                   2.5          0.0
4                    1.0         16.10                   2.5          0.0

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee
0,2,2024-01-01 00:57:55,2024-01-01 01:17:43,1.0,1.72,1.0,N,186,79,2,17.7,1.0,0.5,0.00,0.0,1.0,22.70,2.5,0.00
1,1,2024-01-01 00:03:00,2024-01-01 00:09:36,1.0,1.80,1.0,N,140,236,1,10.0,3.5,0.5,3.75,0.0,1.0,18.75,2.5,0.00
2,1,2024-01-01 00:17:06,2024-01-01 00:35:01,1.0,4.70,1.0,N,236,79,1,23.3,3.5,0.5,3.00,0.0,1.0,31.30,2.5,0.00
3,1,2024-01-01 00:36:38,2024-01-01 00:44:56,1.0,1.40,1.0,N,79,211,1,10.0,3.5,0.5,2.00,0.0,1.0,17.00,2.5,0.00
4,1,2024-01-01 00:46:51,2024-01-01 00:52:57,1.0,0.80,1.0,N,211,148,1,7.9,3.5,0.5,3.20,0.0,1.0,16.10,2.5,0.00
5,1,2024-01-01 00:54:08,2024-01-01 01:26:31,1.0,4.70,1.0,N,148,141,1,29.6,3.5,0.5,6.90,0.0,1.0,41.50,2.5,0.00
6,2,2024-01-01 00:49:44,2024-01-01 01:15:47,2.0,10.82,1.0,N,138,181,1,45.7,6.0,0.5,10.00,0.0,1.0,64.95,0.0,1.75
8,2,2024-01-01 00:26:01,2024-01-01 00:54:12,1.0,5.44,1.0,N,161,261,2,31.0,1.0,0.5,0.00,0.0,1.0,36.00,2.5,0.00
9,2,2024-01-01 00:28:08,2024-01-01 00:29:16,1.0,0.04,1.0,N,113,113,2,3.0,1.0,0.5,0.00,0.0,1.0,8.00,2.5,0.00
10,2,2024-01-01 00:35:22,2024-01-01 00:41:41,2.0,0.75,1.0,N,107,137,1,7.9,1.0,0.5,0.00,0.0,1.0,12.90,2.5,0.00

In [19]:
import pandas as pd

data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

#load data into a DataFrame object:
df = pd.DataFrame(data, index = ['a','b','c'])

print(df)

   calories  duration
a       420        50
b       380        40
c       390        45

In [24]:
#print(df.loc['a':'b'])
print(df.iloc[0])

calories    420
duration     50
Name: a, dtype: int64

In [41]:
import pandas as pd

data = {
  "Duration":{
    "0":60,
    "1":60,
    "2":60,
    "3":45,
    "4":45,
    "5":60
  },
  "Pulse":{
    "0":110,
    "1":117,
    "2":103,
    "3":109,
    "4":117,
    "5":102
  },
  "Maxpulse":{
    "0":130,
    "1":145,
    "2":135,
    "3":175,
    "4":None,
    "5":127
  },
  "Calories":{
    "0":409,
    "1":479,
    "2":340,
    "3":282,
    "4":406,
    "5":None
  }
}

df = pd.DataFrame(data)

print(df)

   Duration  Pulse  Maxpulse  Calories
0        60    110     130.0     409.0
1        60    117     145.0     479.0
2        60    103     135.0     340.0
3        45    109     175.0     282.0
4        45    117       NaN     406.0
5        60    102     127.0       NaN

In [42]:
df.info()

<class 'pandas.DataFrame'>
Index: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  6 non-null      int64
 1   Pulse     6 non-null      int64
 2   Maxpulse  5 non-null      float64
 3   Calories  5 non-null      float64
dtypes: float64(2), int64(2)
memory usage: 246.0 bytes

In [46]:
df_null_row = df.isnull().any(axis=1).sum()
print(df_null_row)

2

In [58]:
new_df = df.dropna()
new_df
print(df['Maxpulse'].mean())
print(df["Calories"].mode())

142.4
0    282.0
1    340.0
2    406.0
3    409.0
4    479.0
Name: Calories, dtype: float64

In [56]:
fill_df = df.fillna({'Maxpulse': df['Maxpulse'].mean(), 'Calories':  df['Calories'].mean()})
fill_df

   Duration  Pulse  Maxpulse  Calories
0        60    110     130.0     409.0
1        60    117     145.0     479.0
2        60    103     135.0     340.0
3        45    109     175.0     282.0
4        45    117     142.4     406.0
5        60    102     127.0     383.2

In [60]:
import pandas as pd
import numpy as np

# Load NYC Taxi data
df = pd.read_parquet("yellow_tripdata_2024-01.parquet")

# ── Essential pandas operations ───────────────────────────────────

# Selecting columns
fares = df["fare_amount"]                           # single column → Series
money_cols = df[["fare_amount", "tip_amount"]]      # multiple → DataFrame

# Filtering rows
valid = df[df["fare_amount"] > 0]                   # simple filter
quality = df[
    (df["fare_amount"] > 0) &                       # AND
    (df["trip_distance"] > 0) &
    (df["passenger_count"] > 0)
]

# Creating new columns
df["trip_duration_min"] = (
    pd.to_datetime(df["tpep_dropoff_datetime"]) -
    pd.to_datetime(df["tpep_pickup_datetime"])
).dt.total_seconds() / 60

df["tip_percentage"] = (
    df["tip_amount"] / df["fare_amount"].replace(0, np.nan) * 100
).round(2)

df["speed_mph"] = (
    df["trip_distance"] / (df["trip_duration_min"] / 60)
).replace([np.inf, -np.inf], np.nan)

# Aggregations — GROUP BY equivalent
hourly_stats = (
    df
    .assign(hour=pd.to_datetime(df["tpep_pickup_datetime"]).dt.hour)
    .groupby("hour")
    .agg(
        trip_count=("fare_amount", "count"),
        avg_fare=("fare_amount", "mean"),
        total_revenue=("total_amount", "sum"),
        avg_tip_pct=("tip_percentage", "mean")
    )
    .round(2)
    .reset_index()
    .sort_values("hour")
)

print(hourly_stats.head(10))

   hour  trip_count  avg_fare  total_revenue  avg_tip_pct
0     0       79094     19.20     2196475.78        19.50
1     1       53627     17.53     1360980.94        20.99
2     2       37517     16.48      903570.92        20.03
3     3       24811     18.15      642753.71        34.85
4     4       16742     22.52      518845.63        16.29
5     5       18764     26.62      679740.60        16.08
6     6       41429     21.65     1222822.32        16.57
7     7       83719     18.54     2188390.99        18.72
8     8      117209     17.65     2953580.60        31.40
9     9      128970     17.71     3288465.07        19.65

In [63]:
# Merge (JOIN equivalent)
# Imagine a lookup table for location names
location_names = pd.DataFrame({
    "location_id": [1, 2, 3],
    "borough": ["Manhattan", "Brooklyn", "Queens"]
})

df_with_names = df.merge(
    location_names,
    left_on="PULocationID",
    right_on="location_id",
    how="left"          # LEFT JOIN — keep all taxi rows
)

df_with_names[df_with_names['PULocationID'].isin([1,2])].head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,...,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,trip_duration_min,tip_percentage,speed_mph,location_id,borough
23213,2,2024-01-01 05:54:58,2024-01-01 05:55:04,1.0,0.00,5.0,N,1,1,1,...,0.0,1.0,109.2,0.0,0.0,0.100000,20.22,0.000000,1.0,Manhattan
24321,2,2024-01-01 06:57:44,2024-01-01 06:57:56,4.0,0.00,3.0,N,1,1,4,...,0.0,-1.0,-24.0,0.0,0.0,0.200000,-0.00,0.000000,1.0,Manhattan
24322,2,2024-01-01 06:57:44,2024-01-01 06:57:56,4.0,0.00,3.0,N,1,1,4,...,0.0,1.0,24.0,0.0,0.0,0.200000,0.00,0.000000,1.0,Manhattan
24323,2,2024-01-01 06:59:32,2024-01-01 06:59:36,4.0,0.00,5.0,N,1,1,1,...,0.0,1.0,96.0,0.0,0.0,0.066667,11.76,0.000000,1.0,Manhattan
24678,2,2024-01-01 06:56:45,2024-01-01 06:56:52,2.0,0.06,5.0,N,1,1,1,...,0.0,1.0,108.0,0.0,0.0,0.116667,20.22,30.857143,1.0,Manhattan